env:
  sumocfg: data/sample_nets/grid.sumocfg
  step_length: 1.0
  gui: false
  tls_ids: ["J0", "J1", "J2", "J3"]
phases:
  J0: ["GrGr", "rGrG"]
  J1: ["GrGr", "rGrG"]
  J2: ["GrGr", "rGrG"]
  J3: ["GrGr", "rGrG"]
